### PR TITLE
Various small fixes

### LINKED ISSUE #280: Some small bugs
- [x] Bug save tent markings
- [x] It should not be possible to replace a tShirt size with the same size

### PR DESCRIPTION
**Pull request by KordonDev**
closes #280

### CODE REVIEW

File: backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt [hunk 1]
```diff
@@ -19,7 +19,8 @@ class DepartmentService(
     private val attendeeService: AttendeeService,
     private val authorityService: AuthorityService,
     private val evacuationGroupService: EvacuationGroupService,
-    private val tentMarkingService: TentMarkingService
+    private val tentMarkingService: TentMarkingService,
+    private val settingsService: SettingsService
```
Comment (KordonDev) [inline backend/src/main/kotlin/de/kordondev/lagermelder/core/service/DepartmentService.kt:23]: remove

File: backend/src/main/kotlin/de/kordondev/lagermelder/core/service/YouthPlanAttendeeRoleService.kt [hunk 2]
```diff
@@ -27,6 +28,9 @@ class YouthPlanAttendeeRoleService(
 
     fun getAttendeeDistribution(): YouthPlanDistribution {
         authorityService.isSpecializedFieldDirector()
+        if (settingsService.canRegistrationFilesDownloaded()) {
```
Comment (KordonDev) [inline backend/src/main/kotlin/de/kordondev/lagermelder/core/service/YouthPlanAttendeeRoleService.kt:31]: needs to be negative

File: backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt [hunk 3]
```diff
@@ -505,7 +505,8 @@ class PlanningFilesService(
 
         departmentWithAttendees.keys.sortedBy { it.headDepartmentName + it.name }.map { department ->
             document.add(Paragraph("${department.headDepartmentName} ${department.name}", headlineFont))
-            document.add(Paragraph("Jugendwart: ${department.leaderName}, EMail: ${department.leaderEMail}, Telefon: ${department.phoneNumber}"))
+            document.add(Paragraph("Jugendwart: ${department.leaderName}, EMail: ${department.leaderEMail}, Telefon während Kreiszeltlager: ${department.phoneNumber}"))
+            document.add(Paragraph("Kommandent: ${department.nameKommandant}, Telefon: ${department.phoneNumberKommandant}"))
```
Comment (KordonDev) [inline backend/src/main/kotlin/de/kordondev/lagermelder/core/service/PlanningFilesService.kt:509]: typo: Kommandant
